**错误内容: RuntimeError: Model class goods.models.GoodsCategory doesn't declare an explicit app_label and isn't**

```python
# 错误原因
from goods.models import Goods
# 使用绝对路径
from apps.goods.models import Goods
```

### Django REST framewrok使用：__str__ returned non-string (type NoneType)错误

**错误**

原文网址: https://blog.csdn.net/zsx1314lovezyf/article/details/100779066

在使用Django REST framewrok序列化的时候，访问接口，出现下面的错误：

![在这里插入图片描述](https://img-blog.csdnimg.cn/20190912175224683.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3pzeDEzMTRsb3Zlenlm,size_16,color_FFFFFF,t_70)

### 出错原因

因为我自己写了User模型，替换了django自带的User，通过继承AbstractUser来完成，并重写了__str__方法，返回了自己的name,并且设置这个name的null==True, 所以导致的这个错误：



```python
 class UserProfile(AbstractUser):
    """
    用户模型类
    """
    name = models.CharField(max_length=30, null=True, blank=True, verbose_name="用户昵称")
    birthday = models.DateField(null=True, blank=True, verbose_name="用户生日")
    mobile = models.CharField(max_length=11, verbose_name="用户手机号码")
    gender = models.CharField(max_length=6, choices=(("male", "男"), ("female", "女")),
                              default="female", verbose_name="用户性别")
    email = models.EmailField(max_length=100, null=True, blank=True, verbose_name="用户邮箱")
 	class Meta:
        db_table = "user_profile"
        verbose_name = "用户模型类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name() ----------->它的问题
```

解决方式：
在自己定义的User模型中__str__方法中返回AbstractUser的get_full_name()或username即可



```python

class UserProfile(AbstractUser):
    """
    用户模型类
    """
    name = models.CharField(max_length=30, null=True, blank=True, verbose_name="用户昵称")
    birthday = models.DateField(null=True, blank=True, verbose_name="用户生日")
    mobile = models.CharField(max_length=11, verbose_name="用户手机号码")
    gender = models.CharField(max_length=6, choices=(("male", "男"), ("female", "女")),
                              default="female", verbose_name="用户性别")
    email = models.EmailField(max_length=100, null=True, blank=True, verbose_name="用户邮箱")
    class Meta:
        db_table = "user_profile"
        verbose_name = "用户模型类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.get_full_name() 或 return self.username
```



### 错误内容:![image-20191225141050821](C:\Users\fjllo\AppData\Roaming\Typora\typora-user-images\image-20191225141050821.png)

**错误原因: 后台服务未开启**

### 错误内容: Access to XMLHttpRequest at 'http://127.0.0.1:8081/categorys/' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**错误原因: 跨域访问,服务器设置了不允许跨域**

### 错误内容: {"non_field_errors":["无法使用提供的认证信息登录。"]}

**错误原因: 自定义用户验证中重写了authenticate方法, 参数少传了一个request 源码中有request,重写的时候也得有,不然post请求接收不到request体,serializer.is_valid()就永远不会验证通过**

## 错误内容:

{

  "detail": "方法 “GET” 不被允许。"

}

**错误原因:views中没有继承viewsets.GenericViewSet**